"""
Django settings for lamla project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
import cloudinary
from dotenv import load_dotenv
from pathlib import Path
from corsheaders.defaults import default_headers

load_dotenv()

# django-environ setup
env = environ.Env()
env.read_env()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

cloudinary.config(
    cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key    = os.getenv('CLOUDINARY_API_KEY'),
    api_secret = os.getenv('CLOUDINARY_API_SECRET'),
    secure=True
)

_allowed_env = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed_env.split(",") if h.strip()]
    if _allowed_env
    else ["localhost", "127.0.0.1"]
)

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # third party
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'corsheaders',
    
    # Locals
    'apps.core',
    'apps.accounts',
    'apps.chatbot',
    'apps.quiz',
    'apps.flashcards',
    'apps.dashboard',
    'apps.materials',
    'apps.subscriptions',
    'apps.clash',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'apps.dashboard.middleware.AnonymousUsageTrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "config.asgi.application"

REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    # Production / local dev with Redis — multi-worker safe
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    # Local dev without Redis — single uvicorn process only
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Database Configuration
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL and not DEBUG:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }

    # Production (Neon requires SSL)
    if not DEBUG:
        DATABASES["default"]["OPTIONS"] = {"sslmode": "require"}

if DEBUG:
    # Local PostgreSQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB_NAME"),
            "USER": os.getenv("POSTGRES_DB_USER"),
            "PASSWORD": os.getenv("POSTGRES_DB_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT"),
            "OPTIONS": {
                "sslmode": "disable"
            }
        }
    }
    
# Add Token authentication to REST framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "auth": "5/hour",    # Auth endpoints (signup, login, verify) - strict
        "contact": "10/hour",  # Contact form / newsletter - prevents email spam
    },
    # Return clean 401s instead of redirecting to login page
    "UNAUTHENTICATED_USER": None,
}

AUTHENTICATION_BACKENDS = [
    'apps.accounts.backend.EmailOrUsernameBackend',  # Supports email & username login
    'django.contrib.auth.backends.ModelBackend',     # Fallback
]


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_NAME="Lamla AI"
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

FASTAPI_BASE_URL = os.getenv("FASTAPI_BASE_URL", "http://localhost:8001")
FASTAPI_BASE_URLS = os.getenv("FASTAPI_BASE_URLS", "")
FASTAPI_URL = FASTAPI_BASE_URL
FASTAPI_SECRET = os.getenv("FASTAPI_SECRET")
CHATBOT_MAX_TOKENS = int(os.getenv("CHATBOT_MAX_TOKENS", "1200"))

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

DEEPSEEK_API_URL = os.getenv("DEEPSEEK_API_URL")

SEARCH_API_KEY= os.getenv("SEARCH_API_KEY")
SEARCH_ENGINE_ID=""
SEARCH_TIMEOUT_SECONDS=5

SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY")

ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")

# Paystack — Phase 1 (donations)
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY", "")   
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY", "") 

# Dashboard emails (contact form, newsletter) — auth emails use EmailJS on the frontend
EMAIL_BACKEND_PRIORITY = os.getenv("EMAIL_BACKEND_PRIORITY")  # brevo, resend, smtp, console
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
BREVO_API_KEY = os.getenv("BREVO_API_KEY")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

AUTH_EMAIL_HOST_USER = os.getenv("AUTH_EMAIL_HOST_USER")
AUTH_EMAIL_HOST_PASSWORD = os.getenv("AUTH_EMAIL_HOST_PASSWORD")

AUTH_USER_MODEL = "accounts.User"

# Welcome and general emails
WELCOME_EMAIL_HOST_USER = os.getenv("WELCOME_EMAIL_HOST_USER")
WELCOME_EMAIL_HOST_PASSWORD = os.getenv("WELCOME_EMAIL_HOST_PASSWORD")


if not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = AUTH_EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = AUTH_EMAIL_HOST_PASSWORD


# CORS / CSRF configuration to allow React frontend
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,https://lamla-ai.vercel.app"
    ).split(",") if origin
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_HEADERS = list(default_headers) + [
    "x-internal-secret"
]

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        ",".join(CORS_ALLOWED_ORIGINS)
    ).split(",") if o
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Enable WhiteNoise to serve static files without Nginx
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
