# Generated by Django 5.2.1 on 2026-05-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_airesponselatency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airesponselatency',
            new_name='dashboard_a_feature_acc43e_idx',
            old_name='dashboard_a_feature_created_idx',
        ),
    ]
