# Generated by Django 5.2.1 on 2026-05-26 22:42

import apps.clash.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=apps.clash.models._generate_room_code, max_length=6, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('num_questions', models.PositiveIntegerField()),
                ('time_per_question', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_clashes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClashParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('is_host', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clash.clashroom')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
